name: System Update

on:
  schedule:
    - cron: '20 * * * *'
  workflow_dispatch:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

jobs:
  update:
    strategy:
      fail-fast: false
      matrix:
        host:
          - jalahalli
          - jalahalli-connector
          - jalahalli-router
          - worldstream
          - worldstream-connector
          - worldstream-router
          - yoginth
          - tsflow
          - ovh
          - adguard
          - umami
    uses: ./.github/workflows/reusable-system-update.yml
    with:
      host: ${{ matrix.host }}
    secrets:
      TS_OAUTH_CLIENT_ID: ${{ secrets.TS_OAUTH_CLIENT_ID }}
      TS_OAUTH_SECRET: ${{ secrets.TS_OAUTH_SECRET }}
